#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-jack"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d60ecd49860c47cc9baf6035a15433dc" }
]

[assets]
directory = "./public"
